# Settings
debug: true
folder: null # The folder to save, to give default settings type null
parts:
 osversion: 
  validity: true
  intestation: "PC_name,OS,OS_version,Date_local,Date_universal_microsecond"
  db:
   enabled: true
   url: "https://harper db name.harperdbcloud.com"
   token: "your token"
   table: "table name"
   change_intestation:
    # for_the_db: for_this_agent
    PC_name: PC_name
    OS: OS
    OS_version: OS_version
    Date_local: Date_local
    Date_universal_microsecond: Date_universal_microsecond
   forced_values:
    module: osversion
    author: "Castellani Davide"
 netinfo: 
  validity: true
  intestation: "PCname,Caption,Description,Status,Manufacturer,Name,GuaranteesDelivery,GuaranteesSequencing,MaximumAddressSize,MaximumMessageSize,SupportsConnectData,SupportsEncryption,SupportsGracefulClosing,SupportsGuaranteedBandwidth,SupportsQualityofService,DNSDomain,DHCPEnabled,IP_Type,DefaultIPGateway,MACAddress,MACAdress_company,Date_local,Date_universal_microsecond"
  MACsep: "-"
  db:
   enabled: true
   url: "https://harper db name.harperdbcloud.com"
   token: "your token"
   table: "table name"
   change_intestation:
    PC_name: PCname
    Caption: Caption
    Description: Description
    Status: Status
    Manufacturer: Manufacturer
    Name: Name
    GuaranteesDelivery: GuaranteesDelivery
    GuaranteesSequencing: GuaranteesSequencing
    MaximumAddressSize: MaximumAddressSize
    MaximumMessageSize: MaximumMessageSize
    SupportsConnectData: SupportsConnectData
    SupportsEncryption: SupportsEncryption
    SupportsGracefulClosing: SupportsGracefulClosing
    SupportsGuaranteedBandwidth: SupportsGuaranteedBandwidth
    SupportsQualityofService: SupportsQualityofService
    DNSDomain: DNSDomain
    DHCPEnabled: DHCPEnabled
    IP_Type: IP_Type
    DefaultIPGateway: DefaultIPGateway
    MACAddress: MACAddress
    MACAdress_company: MACAdress_company
    Date_local: Date_local
    Date_universal_microsecond: Date_universal_microsecond
   forced_values:
    author: "Castellani Davide"
    module: netinfo
 eventsview: 
  validity: true
  intestation: "PCname,User,Category,Type,CategoryString,EventCode,EventIdentifier,EventType,Logfile,RecordNumber,Date_local,Date_universal_microsecond"
  db:
   enabled: true
   url: "https://harper db name.harperdbcloud.com"
   token: "your token"
   table: "table name"
   change_intestation:
    PCname: PCname
    User: User
    Category: Category
    Type: Type
    CategoryString: CategoryString
    EventCode: EventCode
    EventIdentifier: EventIdentifier
    EventType: EventType
    Logfile: Logfile
    RecordNumber: RecordNumber
    Date_local: Date_local
    Date_universal_microsecond: Date_universal_microsecond
   forced_values:
    author: "Castellani Davide"
    module: eventsview
 product: 
  validity: true
  intestation: "PC_name,Caption,Description,IdentifyingNumber,InstallDate,InstallLocation,Language,Name,ProductID,URLInfoAbout,URLUpdateInfo,Vendor,Version,Date_local,Date_universal_microsecond"
  db:
   enabled: true
   url: "https://harper db name.harperdbcloud.com"
   token: "your token"
   table: "table name"
   change_intestation:
    PCname: PC_name
    Caption: Caption
    Description: Description
    IdentifyingNumber: IdentifyingNumber
    InstallDate: InstallDate
    InstallLocation: InstallLocation
    Language: Language
    Name: Name
    ProductID: ProductID
    URLInfoAbout: URLInfoAbout
    URLUpdateInfo: URLUpdateInfo
    Vendor: Vendor
    Version: Version
    Date_local: Date_local
    Date_universal_microsecond: Date_universal_microsecond
   forced_values:
    author: "Castellani Davide"
    module: product
