# Test sync code

name: Sync test

on: [push, pull_request]

jobs:
  # Agentless 
  sync-agentless:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    # Create the DB
    services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: sync
                    MYSQL_ROOT_PASSWORD: syncpws
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Install Database dependencies and test it
      run : |
        sudo apt-get install mysql-client -y
        mysql -uroot -psyncpws -h0.0.0.0 -P49153 -e "SHOW DATABASES;" # Check
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install py3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/requirements.txt
    - name: Test with pytest
      run: |
        pytest
    - name: Log(s)
      run: |
        cat ./log/*
    - name: Print DB(s)
      run: |
        mysql -uroot -psyncpws -h0.0.0.0 -P49153 -e "SHOW TABLES FROM sync;" # Check
        mysql -uroot -psyncpws -h0.0.0.0 -P49153 -e "SELECT * FROM sync.PCname_testfile;" # Show my test table content

  # Agent part 1
  sync-agent-1:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install py3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/requirements.txt
    - name: Test with pytest
      run: |
        sed -i 's/False/True/g' ./bin/test_sync.py # Change test file to make it agent
        pytest
    - name: Log(s)
      run: |
        cat ./log/*
    - name: View file structure
      run: |
        sudo apt install tree
        tree
    - name: Upload file(s)
      run: |
         cat ./flussi/cloned/PCname_testfile.csv > PCname_testfile.csv
    - uses: actions/upload-artifact@v2
      with:
        path: PCname_testfile.csv

  # Agent part 2 
  sync-agent-2:
    needs: sync-agent-1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    # Create the DB
    services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: sync
                    MYSQL_ROOT_PASSWORD: syncpws
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=100

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: Install Database dependencies and test it
      run : |
        sudo apt-get install mysql-client -y
        mysql -uroot -psyncpws -h0.0.0.0 -P49153 -e "SHOW DATABASES;" # Check
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install py3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/requirements.txt
    - name: View file structure
      run: |
        sudo apt install tree
        tree
    - name: Download file(s)
      run: |
         rm ./flussi/testfile.csv
         cp artifact/PCname_testfile.csv ./flussi/cloned/PCname_testfile.csv
    - name: View file structure 2
      run: |
        tree
        cat ./flussi/cloned/PCname_testfile.csv
    - name: Test with pytest
      run: |
        sed -i 's/False/True/g' ./bin/test_sync.py # Change test file to make it agent
        sed -i 's/not/ /g' ./bin/test_sync.py # Change test file to make it agent
        pytest
    - name: Log(s)
      run: |
        cat ./log/*
    - name: Print DB(s)
      run: |
        mysql -uroot -psyncpws -h0.0.0.0 -P49153 -e "SHOW TABLES FROM sync;" # Check
        mysql -uroot -psyncpws -h0.0.0.0 -P49153 -e "SELECT * FROM sync.PCname_testfile;" # Show my test table content
